// Generated by Haxe 4.3.4
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HelloWorld extends haxe.lang.HxObject
{
	public static void main(String[] args)
	{
		haxe.java.Init.init();
		haxe.root.HelloWorld.main();
	}
	
	public HelloWorld(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public HelloWorld()
	{
		//line 3 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		haxe.root.HelloWorld.__hx_ctor__HelloWorld(this);
	}
	
	
	protected static void __hx_ctor__HelloWorld(haxe.root.HelloWorld __hx_this)
	{
	}
	
	
	public static void main()
	{
		//line 5 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		java.lang.System.out.println(((java.lang.Object) ("Hello World") ));
	}
	
	
}


