// Generated by Haxe 4.3.4
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HelloWorld extends haxe.lang.HxObject
{
	public static void main(String[] args)
	{
		haxe.java.Init.init();
		haxe.root.HelloWorld.main();
	}
	
	public HelloWorld(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public HelloWorld()
	{
		//line 1 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		haxe.root.HelloWorld.__hx_ctor__HelloWorld(this);
	}
	
	
	protected static void __hx_ctor__HelloWorld(haxe.root.HelloWorld __hx_this)
	{
	}
	
	
	public static void main()
	{
		//line 3 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Hello World", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"HelloWorld", "HelloWorld.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (3) )) )}));
	}
	
	
}


