// Generated by Haxe 4.3.4
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class MyOptionsThing extends haxe.lang.HxObject
{
	public MyOptionsThing(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public MyOptionsThing()
	{
		//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		haxe.root.MyOptionsThing.__hx_ctor__MyOptionsThing(this);
	}
	
	
	protected static void __hx_ctor__MyOptionsThing(haxe.root.MyOptionsThing __hx_this)
	{
	}
	
	
	public java.lang.String hello;
	
	public boolean goodbye;
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		{
			//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
			if (( field != null )) 
			{
				//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
				switch (field.hashCode())
				{
					case 207022353:
					{
						//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
						if (field.equals("goodbye")) 
						{
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							__temp_executeDef1 = false;
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							this.goodbye = haxe.lang.Runtime.toBool(((java.lang.Boolean) (value) ));
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							return value;
						}
						
						//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
						break;
					}
					
					
					case 99162322:
					{
						//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
						if (field.equals("hello")) 
						{
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							__temp_executeDef1 = false;
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							this.hello = haxe.lang.Runtime.toString(value);
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							return value;
						}
						
						//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		{
			//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
			if (( field != null )) 
			{
				//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
				switch (field.hashCode())
				{
					case 207022353:
					{
						//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
						if (field.equals("goodbye")) 
						{
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							__temp_executeDef1 = false;
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							return this.goodbye;
						}
						
						//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
						break;
					}
					
					
					case 99162322:
					{
						//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
						if (field.equals("hello")) 
						{
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							__temp_executeDef1 = false;
							//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
							return this.hello;
						}
						
						//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		baseArr.push("goodbye");
		//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		baseArr.push("hello");
		//line 7 "C:\\Repos\\samblackburn\\haxe\\HelloWorld.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


