// Generated by Haxe 4.3.4

#pragma warning disable 109, 114, 219, 429, 168, 162
public class HelloWorld : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		global::HelloWorld.main();
	}
	public HelloWorld(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public HelloWorld() {
		global::HelloWorld.__hx_ctor__HelloWorld(this);
	}
	
	
	protected static void __hx_ctor__HelloWorld(global::HelloWorld __hx_this) {
	}
	
	
	public static void main() {
		global::System.Console.WriteLine(((object) ("Hello World") ));
	}
	
	
}


