// Generated by Haxe 4.3.4
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class VarArgsFunction extends haxe.lang.VarArgsBase
{
	public VarArgsFunction(haxe.lang.Function fun)
	{
		//line 48 "C:\\ProgramData\\chocolatey\\lib\\haxe\\haxe_20240304101237_dc1a43d\\std\\java\\internal\\Function.hx"
		super(-1, -1);
		//line 49 "C:\\ProgramData\\chocolatey\\lib\\haxe\\haxe_20240304101237_dc1a43d\\std\\java\\internal\\Function.hx"
		this.fun = fun;
	}
	
	
	public haxe.lang.Function fun;
	
	@Override public java.lang.Object __hx_invokeDynamic(java.lang.Object[] dynArgs)
	{
		//line 53 "C:\\ProgramData\\chocolatey\\lib\\haxe\\haxe_20240304101237_dc1a43d\\std\\java\\internal\\Function.hx"
		return ((java.lang.Object) (this.fun.__hx_invoke1_o(0.0, ( (( dynArgs == null )) ? (new haxe.root.Array(new java.lang.Object[]{})) : (((haxe.root.Array) (haxe.root.Array.ofNative(((java.lang.Object[]) (dynArgs) ))) )) ))) );
	}
	
	
}


